#pragma once

#include <Arduino.h>
#include <vector>

#include "epd_driver.h"

// ---------------------------------------------------------------------------
// Portrait canvas
//
// The panel is physically 960x540 landscape. Everything here is expressed in a
// 540x960 PORTRAIT space that is rotated a quarter turn counter-clockwise on
// its way to the framebuffer, so (0,0) is the top-left of the upright display.
//
// If the picture comes out upside down, the device is being stood on its other
// edge: flip UI_ROTATE_CCW in ui.cpp.
// ---------------------------------------------------------------------------
constexpr int UI_WIDTH  = EPD_HEIGHT;  // 540
constexpr int UI_HEIGHT = EPD_WIDTH;   // 960

// Two colour scales are in play:
//   * shapes take 8-bit values, 0x00 black .. 0xFF white;
//   * text takes 4-bit values, 0 black .. 15 white, because glyph coverage is
//     blended toward the foreground through a 16-entry ramp. That blend is what
//     makes the type anti-aliased.
namespace ink {
constexpr uint8_t kBlack = 0x00;
constexpr uint8_t kDark  = 0x33;
constexpr uint8_t kMid   = 0x77;
constexpr uint8_t kLight = 0xBB;
constexpr uint8_t kPaper = 0xFF;

constexpr uint8_t kTextBlack = 0;
constexpr uint8_t kTextDark  = 3;
constexpr uint8_t kTextMid   = 7;
constexpr uint8_t kTextLight = 10;
constexpr uint8_t kTextPaper = 15;
}  // namespace ink

// Cabin, generated by tools/fontconvert.py. Sizes are pixel heights.
enum class Font {
    Small,      // 18 regular - meta, footers
    SmallBold,  // 18 bold    - small labels
    Body,       // 26 regular - running text
    BodyBold,   // 26 bold    - headings within a block
    Large,      // 36 regular - the quote itself
    Title,      // 36 bold    - screen titles
};

bool uiBegin();

// Resets the canvas to white and starts a new frame for overlap checking.
void uiClearBuffer();

// Pushes the framebuffer to the panel: power on, flash clear, draw, power off.
void uiFlush();

// --- Type -------------------------------------------------------------------

int uiTextWidth(Font font, const char *text);
int uiLineHeight(Font font);
int uiAscender(Font font);
int uiDescender(Font font);  // positive depth below the baseline

// All draw with the baseline at `y`. Returns the x cursor afterwards.
int uiDrawText(Font font, int x, int y, const char *text, uint8_t textColor);
void uiDrawTextRight(Font font, int xRight, int y, const char *text, uint8_t textColor);
void uiDrawTextCenter(Font font, int xCenter, int y, const char *text, uint8_t textColor);

// Greedy word wrap. Splits on spaces only, so long unbroken tokens may overrun.
std::vector<String> uiWrapText(Font font, const String &text, int maxWidth);

// Shortens with a trailing ellipsis until it fits. Use for anything containing
// user data - SSIDs have no length worth trusting.
String uiEllipsize(Font font, const String &text, int maxWidth);

// --- Shapes -----------------------------------------------------------------

void uiFillRect(int x, int y, int w, int h, uint8_t color);
void uiDrawRule(int x, int y, int width, uint8_t color);

// Vertical bar fading from dark at the top to near-paper at the bottom.
void uiDrawAccentBar(int x, int y, int width, int height);

void uiDrawBattery(int x, int y, int percent);

// QR with a 4-module quiet zone, drawn pure black on white. Returns the side
// length in pixels, or 0 if the payload did not fit.
int uiDrawQr(int x, int y, const char *text, int scale);
int uiQrSize(const char *text, int scale);
