#!/usr/bin/env python3
"""Generate a 4-bit anti-aliased font header for the e-paper renderer.

Emits GFXfont / GFXglyph / UnicodeInterval structures matching the display
library's layout, with two pixels per byte (even x in the low nibble) and a
value of 0..15 per pixel where higher means more ink.

Bitmaps are left UNCOMPRESSED on purpose: src/ui.cpp draws glyphs itself, one
pixel at a time, so it can rotate them into the portrait coordinate space. That
blitter reads the bitmap directly and would otherwise have to pull in zlib.

Usage:
    python3 fontconvert.py RobotoBody 26 ~/Library/Fonts/Roboto-Regular.ttf \\
        -o ../src/fonts/roboto_body.h
"""
import argparse
import os

import freetype

# Inclusive code point ranges to build glyphs for.
#
# NOT hand-written. The device is fed UTF-8 exactly as the pipeline produces it,
# and this list is generated from that data so the fonts fit the text rather
# than the text being cut down to fit the fonts:
#
#     npm run export:device
#     node firmware/tools/charset.mjs
#
# Re-run both after changing the dataset or the ranking, and paste the result
# here. Anything the fonts do not cover renders as '?' via ui.cpp, so a codepoint
# that appears in the data and not in this list is a visible bug.
#
# ASCII and Latin-1 are unconditional - they carry the UI's own strings and any
# future quote. The rest is what this corpus actually uses: accented names from
# Polish, Vietnamese, Turkish and Māori, and the typographic punctuation
# Wikiquote writes (em dashes, curly quotes, ellipsis).
INTERVALS = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1 Supplement
    (0x0101, 0x0101),  # ā
    (0x0105, 0x0107),  # ąĆć
    (0x0119, 0x0119),  # ę
    (0x0129, 0x012B),  # ĩĪī
    (0x0131, 0x0131),  # ı
    (0x0142, 0x0144),  # łŃń
    (0x014C, 0x014D),  # Ōō
    (0x0153, 0x0153),  # œ
    (0x015B, 0x015B),  # ś
    (0x0161, 0x0161),  # š
    (0x0169, 0x016D),  # ũŪūŬŭ
    (0x017C, 0x017E),  # żŽž
    (0x02BC, 0x02BC),  # ʼ
    (0x1E6C, 0x1E6C),  # Ṭ
    (0x1EA1, 0x1EA1),  # ạ
    (0x1EA5, 0x1EA5),  # ấ
    (0x2013, 0x2014),  # – —
    (0x2018, 0x2019),  # ‘ ’
    (0x201C, 0x201D),  # “ ”
    (0x2026, 0x2026),  # …
]


def build(face, size):
    face.set_pixel_sizes(0, size)

    bitmaps = bytearray()
    glyphs = []
    intervals = []
    index = 0

    missing = []

    for first, last in INTERVALS:
        intervals.append((first, last, index))
        for cp in range(first, last + 1):
            # A codepoint the face has no outline for silently loads .notdef,
            # which bakes an empty box into the header and looks like a
            # rendering bug on the panel months later. Say so instead.
            if face.get_char_index(cp) == 0:
                missing.append(cp)
            face.load_char(cp, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
            g = face.glyph
            bm = g.bitmap
            w, h = bm.width, bm.rows
            byte_width = w // 2 + w % 2
            offset = len(bitmaps)

            for y in range(h):
                row = bytearray(byte_width)
                for x in range(w):
                    v = bm.buffer[y * bm.pitch + x] >> 4  # 8-bit coverage -> 4-bit
                    if x % 2 == 0:
                        row[x // 2] = (row[x // 2] & 0xF0) | v
                    else:
                        row[x // 2] = (row[x // 2] & 0x0F) | (v << 4)
                bitmaps += row

            advance = g.advance.x >> 6
            if advance > 255:
                raise SystemExit(f"advance_x {advance} exceeds uint8_t at size {size}")

            glyphs.append((w, h, advance, g.bitmap_left, g.bitmap_top, offset))
            index += 1

    if missing:
        listed = " ".join(f"U+{cp:04X}" for cp in missing[:12])
        more = f" (+{len(missing) - 12} more)" if len(missing) > 12 else ""
        print(f"  WARNING: {len(missing)} codepoints absent from this face, "
              f"baked as .notdef: {listed}{more}")

    metrics = (
        face.size.height >> 6,    # advance_y
        face.size.ascender >> 6,  # ascender
        face.size.descender >> 6,  # descender (negative)
    )
    return bitmaps, glyphs, intervals, metrics


def emit(name, bitmaps, glyphs, intervals, metrics, out):
    advance_y, ascender, descender = metrics

    with open(out, "w") as f:
        f.write("// Generated by firmware/tools/fontconvert.py - do not edit.\n")
        f.write("#pragma once\n#include \"epd_driver.h\"\n\n")

        f.write(f"const uint8_t {name}Bitmaps[{len(bitmaps)}] = {{\n")
        for i in range(0, len(bitmaps), 16):
            chunk = ", ".join(f"0x{b:02X}" for b in bitmaps[i:i + 16])
            f.write(f"    {chunk},\n")
        f.write("};\n\n")

        f.write(f"const GFXglyph {name}Glyphs[] = {{\n")
        for w, h, adv, left, top, off in glyphs:
            f.write(f"    {{ {w}, {h}, {adv}, {left}, {top}, 0, {off} }},\n")
        f.write("};\n\n")

        f.write(f"const UnicodeInterval {name}Intervals[] = {{\n")
        for first, last, idx in intervals:
            f.write(f"    {{ 0x{first:X}, 0x{last:X}, 0x{idx:X} }},\n")
        f.write("};\n\n")

        f.write(f"const GFXfont {name} = {{\n")
        f.write(f"    (uint8_t *){name}Bitmaps,\n")
        f.write(f"    (GFXglyph *){name}Glyphs,\n")
        f.write(f"    (UnicodeInterval *){name}Intervals,\n")
        f.write(f"    {len(intervals)},\n")
        f.write("    false,\n")
        f.write(f"    {advance_y},\n    {ascender},\n    {descender},\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("name", help="C identifier for the font")
    ap.add_argument("size", type=int, help="pixel size")
    ap.add_argument("ttf", help="source TrueType file")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("-i", "--index", type=int, default=0,
                    help="face index within a .ttc collection (see --list)")
    ap.add_argument("--list", action="store_true",
                    help="print the faces in the file and exit")
    ap.add_argument("--instance", type=int, default=0,
                    help="named instance of a variable font, 1-based "
                         "(Cabin: 1=Regular, 4=Bold). 0 leaves the default.")
    args = ap.parse_args()

    path = os.path.expanduser(args.ttf)

    # macOS ships its classic families as .ttc collections, where the weights
    # live side by side in one file and index 0 is not necessarily Regular.
    if args.list:
        count = freetype.Face(path).num_faces
        for i in range(count):
            f = freetype.Face(path, index=i)
            print(f"  {i}: {f.family_name.decode()} - {f.style_name.decode()}")
        return

    face = freetype.Face(path, index=args.index)

    # Variable fonts default to their Regular instance, so a bold cut has to be
    # selected explicitly or every weight comes out identical.
    if args.instance:
        face.set_var_named_instance(args.instance)

    bitmaps, glyphs, intervals, metrics = build(face, args.size)
    emit(args.name, bitmaps, glyphs, intervals, metrics, args.out)

    print(f"{args.out}: {len(glyphs)} glyphs, {len(bitmaps)} bytes, "
          f"advance_y={metrics[0]} ascender={metrics[1]} descender={metrics[2]}")


if __name__ == "__main__":
    main()
